// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/app-tecnico/Dettaglio.tsx": () => import("../components/mockups/app-tecnico/Dettaglio.tsx"),
  "./components/mockups/app-tecnico/Login.tsx": () => import("../components/mockups/app-tecnico/Login.tsx"),
  "./components/mockups/app-tecnico/Richieste.tsx": () => import("../components/mockups/app-tecnico/Richieste.tsx")
};
